apiVersion: triliovault.trilio.io/v1
kind: BackupPlan
metadata:
  name: wordpress-label-backupplan
spec:
  backupNamespace: wordpress
  backupConfig:
    target:
      namespace: default
      name: sample-target
    retentionPolicy:
      namespace: default
      name: demo-policy
  backupPlanComponents:
    custom:
      - matchLabels:
          app: wordpress
